### ISSUE TITLE
query_and_build fails upon empty response body

### ISSUE THREAD

**Issue by eiked** [buntine/discogs#38]
some queries like edit_listing do not return a response body but only a http status code.

response.body => ""

query_and_build than fails in
    hash = JSON.parse(data)

with
    JSON::ParserError: A JSON text must at least contain two octets!
    from /opt/local/lib/ruby2.1/2.1.0/json/common.rb:155:in `initialize'

Instead either nil or an empty Hash should be returned.
I opt for returning an empty Hash when the response.code was in the 200 OK range,
but to return nil when the request failed

**Comment by buntine** [comment]
Fixed. I still need to add some tests, but closing this now.
