### ISSUE TITLE
Image URIs blank after gem upgrade

### ISSUE THREAD

**Issue by GordonDiggs** [buntine/discogs#44]
I'm using the `uri` field on release images as follows:

```ruby
wrapper = Discogs::Wrapper.new(...)
wrapper.get_release(id)
release.images
```

In version 2.1.1, the `uri` field is present, but is a blank string after updating to 2.1.5. I think I'll look more into this later but wanted to open the issue in case you had any ideas before I did.

**Comment by buntine** [comment]
Thanks. I'll take a look at this ASAP.

**Comment by buntine** [comment]
Hey Gordon,

Are you authenticated (via oAuth) when you make the request? Recently(ish), Discogs changed their API so image requests require authentication.

Andrew

**Comment by GordonDiggs** [comment]
@buntine I am not - that might be what the issue is! [This is the invocation of the API](https://github.com/GordonDiggs/rayons/blob/master/app/models/discogs_release.rb#L11). I will try authenticating and see if that helps!

**Comment by buntine** [comment]
Cool. I will close this now, let me know if that does not fix it, though, and we can reopen this.
