### ISSUE TITLE
Invalid Request Token

### ISSUE THREAD

**Issue by Pierre-Staszak** [buntine/discogs#52]
Hello,
When I try to authenticate to Discogs API, using `access_token = @discogs.authenticate(request_token, verifier)`

I get the error :
"OAuth::Error in DiscogsWrapperController#callback
Invalid Request Token"

Edit : it seems that the session[:request_token] isn't considered as an OAuth::RequestToken anymore when we are in the callback function

Can you help me please ? I'm using the same code as you in the auth examples

**Comment by buntine** [comment]
Hey Pierre,

I have just updated some of the dependencies on the discogs-oauth application. 

I tested the app and it worked correctly for me. I was able to authenticate via oAuth2 without an issue.

To troubleshoot, try testing that sessions are working in your app. If using  "localhost", you may have some issues in browsers not trusting the session. Try 127.0.0.1 instead.

Also, clone the discogs-oauth app (https://github.com/buntine/discogs-oauth) (or git pull if oyu already have it) and follow the setup instructions. Let me know if that does not work for you and which error you are receiving.

cheers,
Andrew.

**Comment by buntine** [comment]
Closing as it's been resolved off-site and is not an issue with this codebase. :)

**Comment by jamesbvaughan** [comment]
@PierreCooper Do you remember what the solution to this was? I am running into the exact same thing and I can't figure out why the session[:request_token] isn't considered as an OAuth::RequestToken anymore when we are in the callback function.

**Comment by PierreCooper** [comment]
@jamesbvaughan Hey there ! I honestly don't remember what I did precisely, but it seems that using the gem "activerecord-session_store" resolved the issue. Good luck !
