### ISSUE TITLE
Pagination at raw calls

### ISSUE THREAD

**Issue by rtuz2th** [buntine/discogs#55]
There are parts of the api you can only fetch using the raw method that accept pagination, for example if you parse the versions_url of a master release. Raw does not accept any parameters and I tried but could not fix this myself. Could someone please implement this?

**Comment by buntine** [comment]
I will take a look for you.

**Comment by buntine** [comment]
FYI, version 2.5.1 of the gem will allow for optional additional params to be passed to `raw` calls. I'll release it shortly.
