### ISSUE TITLE
list_order_messages

### ISSUE THREAD

**Issue by smart-web-rock** [buntine/discogs#57]
It seems slash is missing in list_order_messages method.
query_and_build "marketplace/orders#{order_id}/messages", pagination
I think it should be edited like this.
query_and_build "marketplace/orders/#{order_id}/messages", pagination

**Comment by buntine** [comment]
Great, thanks, feel free to submit a pull request and I'll merge it in. Otherwise, I'll make the change myself soon. :)

**Comment by smart-web-rock** [comment]
I appreciate it if you would make the change ASAP. I am using your gem in urgent project, Thanks

**Comment by buntine** [comment]
Version 2.5.0 has just been published that fixes this issue: https://rubygems.org/gems/discogs-wrapper/versions/2.5.0

Please update your gem and let me know if you have any issues.

**Comment by smart-web-rock** [comment]
Thanks very much.
