### ISSUE TITLE
BUG: NameError: undefined method `type_' for class `Hashie::Mash'

### ISSUE THREAD

**Issue by khanimdad** [buntine/discogs#58]
@buntine any idea on below error?

NameError: undefined method `type_' for class `Hashie::Mash'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:342:in `method'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:342:in `log_built_in_message'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:148:in `custom_writer'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:217:in `block in deep_update'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:210:in `each_pair'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:210:in `deep_update'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:124:in `initialize'
	from /var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/hashie-3.5.5/lib/hashie/mash.rb:327:in

**Comment by buntine** [comment]
It looks like a bug with Hashie. Do you have any code samples that triggered this issue?

**Comment by khanimdad** [comment]
I did a monkey patch like below and its working now, let me know you though

`class Discogs::Wrapper
  # Replaces known conflicting keys with safe names in a nested hash structure.
  def sanitize_hash(hash)
    conflicts = {"count" => "total"}
    result = {}

    for k, v in hash
      safe_name = conflicts[k]

      if safe_name
        # BC: Temporary set original key for backwards-compatibility.
        warn "[DEPRECATED]: The key '#{k}' has been replaced with '#{safe_name}'. When accessing, please use the latter. This message will be removed in the next major release."
        result[k] = v
        # End BC

        result[safe_name] = v
        k = safe_name
      else
        result[k] = v
      end

      if v.is_a?(Hash)
        result[k] = sanitize_hash(result[k])
      end
    end

    **if result.keys.include?('tracklist')
      result['tracklist'].collect do |r|
          r.delete("type_")
          r.merge("type" => v)
      end
    end**
    result
  end	
end	`

**Comment by buntine** [comment]
@khanimdad I think an easier approach would be to add "type_" to the conflicts hash and the rest should just work:

```
 conflicts = {"count" => "total",
                   "type_" => "type"}
```

**Comment by khanimdad** [comment]
@buntine you can reproduce by calling

`wrapper.get_master(source_id)`

First i tried your suggested approach but the problem is that "type_" key not at top level but under "tracklist" key.

**Comment by buntine** [comment]
Ok, thanks. I am surprised that it does not work because that method (`sanitize_hash`) is recursive, so it should work on nested keys.

**Comment by buntine** [comment]
Fixed in merged PR above.
