### ISSUE TITLE
New User, Config Help Please

### ISSUE THREAD

**Issue by VinylVault** [buntine/discogs#59]
Hi All,

I'm new-ish to RoR, I have written PHP before, and cURL'd the discogs API.

I have added and bundled the Gem, but am wondering where I am supposed to add

wrapper = Discogs::Wrapper.new("Test OAuth", user_token: "my_user_token")
results = wrapper.search("Nick Cave")

Adding to the controller .rb file I get the following error

NameError in ShelvesController#index
uninitialized constant ShelvesController::Discogs

It's probably me being particularly incapable with Ruby (as i said I'm still learning), but any help would be appreciated as its not particularly clear in the docs, where to add the stubs, and how to display the responses

I should add, I'm not planning to use oAuth, as there will be no public facing API access, only through the admin panel when updating the local database

Ta

**Comment by VinylVault** [comment]
Hi All,

I'm new-ish to RoR, I have written PHP before, and cURL'd the discogs API.

I have added and bundled the Gem, but am wondering where I am supposed to add

```
wrapper = Discogs::Wrapper.new("Test OAuth", user_token: "my_user_token")
results = wrapper.search("Nick Cave")
```

Adding to the controller .rb file I get the following error

```
NameError in ShelvesController#index
uninitialized constant ShelvesController::Discogs
```
It's probably me being particularly incapable with Ruby (as i said I'm still learning), but any help would be appreciated as its not particularly clear in the docs, where to add the stubs, and how to display the responses

Ta

**Comment by buntine** [comment]
Hey there, have you added the `discogs-wrapper` gem to your `Gemfile`?

Rails should automatically be loading it for you.

**Comment by VinylVault** [comment]
hi @buntine yes its in my ```gemfile```

**Comment by buntine** [comment]
Ok, can you get into a rails console and see if it works in there? Make
sure you have run the "bundle install" command first.

It is also possible that you need to "require" the library before using it,
although my memory of rails is telling me that that is done automatically.

**Comment by buntine** [comment]
You may also want to check out this repo, which gives an example of using
the gem in a rails app: https://github.com/buntine/discogs-oauth

**Comment by VinylVault** [comment]
sure can what do you want me to run
```
rails c [for console]
reload!
```
then what?

**Comment by buntine** [comment]
I am on my phone so this may get garbled, but:

$ bundle install
$ bundle exec rails C
> Discogs::Wrapper.new("test")

**Comment by VinylVault** [comment]
> You may also want to check out this repo, which gives an example of using the gem in a rails app: https://github.com/buntine/discogs-oauth
> […](#)

already tried looking at it, but the bundle install failed on me - will try again though and report errors

I'm in the console, what do you want to me to run?

**Comment by buntine** [comment]
Discogs::Wrapper.new("test")

**Comment by VinylVault** [comment]
```
Discogs::Wrapper.new("test")
=> #<Discogs::Wrapper:0x000055893718b620 @app_name="test", @access_token=nil, @user_token=nil>
```

**Comment by buntine** [comment]
That means it works. So now that you have successfully run 'bundle
install', you should be able to run "bundle exec rails s" and the app
should work.

**Comment by VinylVault** [comment]
what confuses me, is that's exactly what I did yesterday, before I created the issue, literally step by step and now it works, in the limited way I've tested it so far, thanks for the help so far @buntine , i'm sure there will be more needed
