### ISSUE TITLE
Question: Rate limiting headers

### ISSUE THREAD

**Issue by johanbaaij** [buntine/discogs#61]
Would it be practical at all to include the [Rate limiting headers](https://www.discogs.com/developers#page:home,header:home-rate-limiting) that Discogs provides to the Discogs::Wrapper responses?

**Comment by buntine** [comment]
I'll take a look for you ASAP.

**Comment by johanbaaij** [comment]
Cool, I'm also happy to have a go at it. A good start could be adding an exception for error code 429?

Not too sure what the best way is to include the actual headers. It would be pretty easy to add them to the Hashie responses but that doesn't seem quite right.

**Comment by buntine** [comment]
Version 2.5.1 of the gem, which I will release shortly, adds support for the rate limited error response (429). I will add in the rate_liimt headers into the mashie response in the next major revision. I'll release that soon also.

Sorry for the delay.

**Comment by buntine** [comment]
Ok, released 2.5.1
